# Generated by Django 3.2.16 on 2023-08-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230801_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Количетсво ингредиентов в рецепте', 'verbose_name_plural': 'Количетсво ингредиентов в рецепте'},
        ),
    ]
