# Generated by Django 3.2.16 on 2023-08-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230719_0655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
